name: CI
on: [push]

jobs:
  build-rpms:
    name: Build RPMS
    runs-on: ubuntu-latest
    container: centos:7

    steps:
    - name: Install rpmbuild
      run: yum -y install rpm-build

    - name: Run rpmbuild
      run: make
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: rpms
        path: RPMS/

  test-centos-install:
    name: Test CentOS 7 installs
    runs-on: ubuntu-latest
    needs: build-rpms
    container: centos:${{ matrix.centos-version }}
    strategy:
      matrix:
        centos-version: [
          '7.1.1503',
          '7.2.1511',
          '7.3.1611',
          '7.4.1708',
          '7.5.1804',
          '7.6.1810'
        ]

    steps:
    - name: Fail install devtoolset-3 without vault
      run: |
        yum install -y centos-release-scl
        yum install -y devtoolset-3 && exit 1 || exit 0

    - name: Download RPMS
      uses: actions/download-artifact@v2
      with:
        name: rpms
        path: RPMS/

    - name: Install devtoolset-3 with vault
      run: |
        yum install -y RPMS/*
        yum install -y --skip-broken devtoolset-3
